version: '2'
services:
    health-postgresql:
        container_name: health-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/health/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=health
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
